source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target'Swift_weixin' do
    pod 'Alamofire'
    
    # 'node_modules'目录一般位于根目录中
    # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
    pod 'React', :path => './RNComponent/node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    'DevSupport',
    'RCTActionSheet',
    'RCTAdSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'BatchedBridge',
    'RCTAnimation',
    
    # 这个模块是用于调试功能的
    # 在这里继续添加你所需要的模块
    ]
    # 如果你的RN版本 >= 0.42.0，请加入下面这行
    pod "Yoga", :path => "./RNComponent/node_modules/react-native/ReactCommon/yoga"
end
